### ISSUE TITLE
CA Labs mutex lock fails silently

### ISSUE THREAD

**Issue by brian-stravaro** [epics-extensions/CALab#10]
There are two lock() functions in calabs.cpp to protect some of the internal data structures.
These locks will loop as quickly as possible for ten seconds to try to obtain the lock.
If the lock fails, it does so silently, so there is no way for the caller to know that it doesn't have the lock.
The most likely reason for this to fail is because the system is so overloaded that it can't keep up.

I propose that lock() should return an error code, so that the callers can report errors to the user.

I think I will also see if we can reduce the amount of time we have the mutex, to make it easier to obtain in other threads.

**Comment by ralphlange** [comment]
+1

I strongly agree. Spinlocks can have dangerous side effects and should only be used for situations where the locks can only be held for a very short time. (E.g. to protect ring buffers.)

**Comment by brian-stravaro** [comment]
In dealing with a lot of PVs (in my case, about 50,000), I reliably fail to get the lock which controls access to the big linked list of PVs.
It's kind of slow to add a new one, since the list is unordered and it does a comparison of all existing PV names before adding the new one.
I'm inclined to replace the linked list with a std::map with the PV name as key.
The map still needs to be protected with a mutex, but the lookups will be much faster.

**Comment by brian-stravaro** [comment]
There's also a mutex called "getLock", and I'm not entirely sure what it's meant to protect. It's used in the getValue() call, where most of the data it is operating on is state information that's passed in from the caller.

**Comment by ralphlange** [comment]
+1 for replacing the linked list. You could try to use std::unordered_map where it exists.

**Comment by nugatritter** [comment]
**Here is some background on the topic before changes should be considered.**

Ca Lab has only one instance for each EPICS variable. It does not matter whether this variable is read, written or used in a user event. When a variable is now read and written, the same instance of the variable is used. 

Because each variable within CA Lab subscribes to the corresponding Channel Access channel of EPICS and thus automatically always receives current values, read requests from LabVIEW can be answered extremely quickly. 

To LabVIEW can directly access the instantiated EPICS variables within CA Lab, it gets the direct memory address. Within Ca Lab this address is validated and the corresponding request is answered directly. This eliminates the time-consuming search of all known variables with each LabVIEW access to CA Lab. For this reason, a linked list was used in CA Lab.

Since a variable can be read and written by different VIs at the same time, but exists only as one instance, it is protected with a lock. It therefore processes each request in a self-contained manner one after the other. This ensures data consistency.

Because during a session new variables can be added and thus the linked list with the known variables changes, additionally the functions were secured with a lock, which depend on a stable variable list.

Here, however, the weakness of the system becomes clear. If very many variables (>10,000) are created and there is a lot of traffic, then these "locks" slow down the system. At HZB, we have not yet had an application with LabVIEW that processes such a large number of variables, so this was not noticed at all. But now we have this case and it is a chance to bring CA Lab to a new level. Ideas for solving the problem are very welcome.

**Comment by ralphlange** [comment]
Thanks a lot for that information, Carsten.
No offense!

The _known variables list_ topic is a typical scaling issue and shows a valid approach (linked list) that is good until it breaks when used with too many elements. Using a `std::unordered_map` will be a good implementation (probably hash bucket list) with equal performance for short and long lists.

Note that `std::unordered_map` keeps some iterators and pointers to elements valid through map operations, so there is a chance some of the function locks could even be dropped.
Generally, global locks are often killing performance in a multi-threaded context. This becomes a scaling issue if operations need more time when used on larger structures (like when using a linked list).

The _spinlocks_ are appropriate for securing read and write access to a single variable, no question. (As long as there is a lock per variable.) Array types would need to be argued. Copy operations might be too long if we're talking about GB-size images, but a pointer swap (or `std::move`) would always be fine.
As spinlocks and mutexes are more or less two implementations of the same concept, the API should be similar. (Cf. [epicsSpin.h](https://github.com/epics-base/epics-base/blob/7.0/modules/libcom/src/osi/epicsSpin.h))

**Comment by nugatritter** [comment]
@brian-stravaro Unfortunately I can't recreate the problem, so it would be helpful to know where exactly the timeout occurs. Is it the lock() of the individual PV or is it a lock() of a global function?

**Comment by nugatritter** [comment]
@ralphlange Are you sure that a `std::unordered_map` will keep its elements in the same place in memory even if it grows?

**Comment by ralphlange** [comment]
From https://en.cppreference.com/w/cpp/container/unordered_map:

> References and pointers to either key or data stored in the container are only invalidated by erasing that element, even when the corresponding iterator is invalidated.

**Comment by nugatritter** [comment]
I think the problem is less with the lists than with the many parallel accesses to the global functions.

**Comment by ralphlange** [comment]
Brian wrote (above):
>  I reliably fail to get the lock which controls access to the big linked list of PVs.

which sounds like he is talking about the global lock.

**Comment by brian-stravaro** [comment]
Thanks for the background, Carsten. That confirms some of what I was thinking.
The lock I was failing to get is called "myItems.myLock", and it is basically myItems.add() competing with caTask() on access to the linked list of 50,000 caLabItems.
As Ralph mentioned, the std::unordered_map has some good traits in that it only invalidates pointers and iterators in obvious situations. We still need a lock to manage some of it.

To be clear, there are two global locks. One is myItems.myLock mentioned above. The other is the "getLock", which ensures that the process of getting values is serialized. I'm not sure what exactly is being protected. This information from Carsten seems relevant, but my brain is still missing some of the details:

> Since a variable can be read and written by different VIs at the same time, but exists only as one instance, it is protected with a lock. It therefore processes each request in a self-contained manner one after the other. This ensures data consistency.

The getLock only protects the "getValue()" callback, so I'm not sure it prevents parallel writes.  The gets themselves have different memory that they are operating with. There are some allItemsConnected1/2 globals that are protected, but I don't quite follow what role they play.  So in short, I'm not understanding the whole picture and need to spend more time with the code to figure that out.

**Comment by nugatritter** [comment]
Yes, the getLock only protects the "getValue()" callback, and it prevents parallel writes in the case of NoMEL is true. But on second thought, the myItems.myLock should be sufficient in this case as well.

**Comment by nugatritter** [comment]
I started to replace the linked list with `std::unordered_map`, but I didn`t finish today. I will not be able to take care of it again until July 1, 2022

**Comment by brian-stravaro** [comment]
I also started on this today. (Sorry for the duplicated effort.) I'll try to get it working by the time you return so that you can review it.

**Comment by brian-stravaro** [comment]
I just pushed a first pass implementation to the lock-improvements branch. It compiles and runs on Linux.
Caveat: It hasn't been thoroughly tested, nor have I compiled it yet on Windows.
It appears to be significantly faster (10x to 100x) at initializing the PVs in my 50k PV use case.
More cleanup and testing to come, but eventually I'd like to get a few people to review the changes.
