### ISSUE TITLE
labview could not get pv of ioc after the ioc reboot

### ISSUE THREAD

**Issue by l123173** [epics-extensions/CALab#20]
Hi, 
    Thank you for your caLab program.
    
    Recently, we met a question.
    We use caLab of labview(in windows) to get pv, it works well. 
    But calab could not get pv after we reboot the ioc (in Linux).  it is the same ioc and same pv.
    The only way to conncet the pv was reboot  the windows pc. Reboot the linux pc did not work.
    
    Could you give me some help to avoid reboot windoes pc?  We try to up/down the network connection of windows, it did not work.

Regards,
Lynn

**Comment by nugatritter** [comment]
Hi Lynn,
I have just tested CA Lab again. If I use an external Soft IOC and stop and restart it while the CA Lab client is running, the CA Lab client reconnects with a delay of some seconds.
Unfortunately I cannot say why the connection is not restored in your case. But instead of a reboot, I recommend a `CA Lab Disconnect` at the end of the VI programme. This should allow the variables to be re-initialised when the VI is restarted.
I hope this helps.
Best regards,
Carsten

**Comment by nugatritter** [comment]
No further feedback? Okay, then this thread will now be closed.
